## Pandas for AI/ML: Essential Functions and Methods

This notebook provides an overview of key pandas functionalities frequently used in Artificial Intelligence and Machine Learning workflows, along with explanations and practical examples.

In [1]:
import pandas as pd
import numpy as np

# Let's start by creating a sample DataFrame for demonstration purposes
data = {
    'Feature_A': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
    'Feature_B': [1.1, 2.2, np.nan, 4.4, 5.5, 6.6, 7.7, np.nan, 9.9, 10.0],
    'Category': ['A', 'B', 'A', 'C', 'B', 'A', 'C', 'B', 'A', 'C'],
    'Target': [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
    'Date': pd.to_datetime(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08', '2023-01-09', '2023-01-10'])
}
df = pd.DataFrame(data)

print("Sample DataFrame created:")
display(df)

Sample DataFrame created:

   Feature_A  Feature_B Category  Target       Date
0         10        1.1        A       0 2023-01-01
1         20        2.2        B       1 2023-01-02
2         30        NaN        A       0 2023-01-03
3         40        4.4        C       1 2023-01-04
4         50        5.5        B       0 2023-01-05
5         60        6.6        A       1 2023-01-06
6         70        7.7        C       0 2023-01-07
7         80        NaN        B       1 2023-01-08
8         90        9.9        A       0 2023-01-09
9        100       10.0        C       1 2023-01-10

### 1. Data Loading

Loading data is the first step. Pandas supports various file formats.

In [2]:
# Example: Loading from CSV (assuming 'sample_data.csv' exists)
# df_csv = pd.read_csv('sample_data.csv')

# Example: Loading from Excel (assuming 'sample_data.xlsx' exists)
# df_excel = pd.read_excel('sample_data.xlsx')

# Example: Loading from a dictionary (as done above)
# This is useful for creating dataframes programmatically or from JSON-like structures.
print("Our sample DataFrame 'df' was loaded from a Python dictionary.")

Our sample DataFrame 'df' was loaded from a Python dictionary.

### 2. Basic Data Exploration

Understanding your data's structure and content is crucial.

In [3]:
# .head() / .tail(): View the first/last N rows
print("First 3 rows:")
display(df.head(3))

print("\nLast 2 rows:")
display(df.tail(2))

# .info(): Get a summary of the DataFrame including data types and non-null values
print("\nDataFrame Info:")
df.info()

# .describe(): Generate descriptive statistics for numerical columns
print("\nDescriptive Statistics:")
display(df.describe())

# .shape: Get the number of rows and columns
print(f"\nDataFrame Shape: {df.shape} (rows, columns)")

# .columns: Get column names
print(f"\nColumn Names: {df.columns.tolist()}")

# .value_counts(): Count unique values in a Series
print("\nValue counts for 'Category':")
display(df['Category'].value_counts())

First 3 rows:

   Feature_A  Feature_B Category  Target       Date
0         10        1.1        A       0 2023-01-01
1         20        2.2        B       1 2023-01-02
2         30        NaN        A       0 2023-01-03

Last 2 rows:

   Feature_A  Feature_B Category  Target       Date
8         90        9.9        A       0 2023-01-09
9        100       10.0        C       1 2023-01-10

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Feature_A  10 non-null     int64
 1   Feature_B  8 non-null      float64
 2   Category   10 non-null     object
 3   Target     10 non-null     int64
 4   Date       10 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(1)
memory usage: 532.0+ bytes

Descriptive Statistics:

        Feature_A  Feature_B     Target                 Date
count   10.000000   8.000000  10.000000                   10
mean    55.000000   5.925000   0.500000  2023-01-05 12:00:00
min     10.000000   1.100000   0.000000  2023-01-01 00:00:00
25%     32.500000   3.850000   0.000000  2023-01-03 06:00:00
50%     55.000000   6.050000   0.500000  2023-01-05 12:00:00
75%     77.500000   8.250000   1.000000  2023-01-07 18:00:00
max    100.000000  10.000000   1.000000  2023-01-10 00:00:00
std     30.276504   3.287965   0.527046                  NaN

DataFrame Shape: (10, 5) (rows, columns)

Column Names: ['Feature_A', 'Feature_B', 'Category', 'Target', 'Date']

Value counts for 'Category':

Category
A    4
B    3
C    3
Name: count, dtype: int64

### 3. Handling Missing Values

Missing data (`NaN`) is common and needs to be addressed before modeling.

In [4]:
# .isnull() / .notnull(): Detect missing values
print("DataFrame with null indications:")
display(df.isnull().head())

# .isnull().sum(): Count missing values per column
print("\nNumber of missing values per column:")
display(df.isnull().sum())

# .dropna(): Remove rows or columns with missing values
# Removing rows with any NaN
df_dropped_rows = df.dropna()
print("\nDataFrame after dropping rows with any NaN:")
display(df_dropped_rows)

# Removing columns with any NaN (use axis=1 or axis='columns')
# df_dropped_cols = df.dropna(axis=1)

# .fillna(): Fill missing values with a specified value or method
# Fill with a constant value (e.g., 0 or mean/median)
df_filled_zero = df.fillna(0)
print("\nDataFrame after filling NaN with 0:")
display(df_filled_zero)

# Fill with the mean of the column
df_filled_mean = df.copy()
df_filled_mean['Feature_B'] = df_filled_mean['Feature_B'].fillna(df_filled_mean['Feature_B'].mean())
print("\nDataFrame after filling 'Feature_B' NaN with its mean:")
display(df_filled_mean)

# Forward fill (ffill) or backward fill (bfill)
df_ffill = df.fillna(method='ffill')
print("\nDataFrame after forward-filling NaN:")
display(df_ffill)

DataFrame with null indications:

   Feature_A  Feature_B  Category  Target   Date
0      False      False     False   False  False
1      False      False     False   False  False
2      False       True     False   False  False
3      False      False     False   False  False
4      False      False     False   False  False

Number of missing values per column:

Feature_A    0
Feature_B    2
Category     0
Target       0
Date         0
dtype: int64

DataFrame after dropping rows with any NaN:

   Feature_A  Feature_B Category  Target       Date
0         10        1.1        A       0 2023-01-01
1         20        2.2        B       1 2023-01-02
3         40        4.4        C       1 2023-01-04
4         50        5.5        B       0 2023-01-05
5         60        6.6        A       1 2023-01-06
6         70        7.7        C       0 2023-01-07
8         90        9.9        A       0 2023-01-09
9        100       10.0        C       1 2023-01-10

DataFrame after filling NaN with 0:

   Feature_A  Feature_B Category  Target       Date
0         10        1.1        A       0 2023-01-01
1         20        2.2        B       1 2023-01-02
2         30        0.0        A       0 2023-01-03
3         40        4.4        C       1 2023-01-04
4         50        5.5        B       0 2023-01-05
5         60        6.6        A       1 2023-01-06
6         70        7.7        C       0 2023-01-07
7         80        0.0        B       1 2023-01-08
8         90        9.9        A       0 2023-01-09
9        100       10.0        C       1 2023-01-10

DataFrame after filling 'Feature_B' NaN with its mean:

   Feature_A  Feature_B Category  Target       Date
0         10      1.100        A       0 2023-01-01
1         20      2.200        B       1 2023-01-02
2         30      5.925        A       0 2023-01-03
3         40      4.400        C       1 2023-01-04
4         50      5.500        B       0 2023-01-05
5         60      6.600        A       1 2023-01-06
6         70      7.700        C       0 2023-01-07
7         80      5.925        B       1 2023-01-08
8         90      9.900        A       0 2023-01-09
9        100     10.000        C       1 2023-01-10

DataFrame after forward-filling NaN:

/tmp/ipykernel_740/2227427878.py:31: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_ffill = df.fillna(method='ffill')

   Feature_A  Feature_B Category  Target       Date
0         10        1.1        A       0 2023-01-01
1         20        2.2        B       1 2023-01-02
2         30        2.2        A       0 2023-01-03
3         40        4.4        C       1 2023-01-04
4         50        5.5        B       0 2023-01-05
5         60        6.6        A       1 2023-01-06
6         70        7.7        C       0 2023-01-07
7         80        7.7        B       1 2023-01-08
8         90        9.9        A       0 2023-01-09
9        100       10.0        C       1 2023-01-10

### 4. Data Selection with `loc` and `iloc`

These are fundamental for selecting data by label (`loc`) or by integer position (`iloc`).

#### `loc` (Label-based indexing)
Used for selecting data by row and column labels. It includes the end label.

`df.loc[row_label, column_label]`

In [5]:
# Select a single row by index label
print("Row with label 0:")
display(df.loc[0])

# Select multiple rows by index labels
print("Rows with labels 0, 2, 5:")
display(df.loc[[0, 2, 5]])

# Select a slice of rows by label (inclusive)
print("Rows from label 2 to 5 (inclusive):")
display(df.loc[2:5])

# Select rows and specific columns by label
print("Rows 0 to 3, columns 'Feature_A' and 'Category':")
display(df.loc[0:3, ['Feature_A', 'Category']])

# Select all rows, specific columns
print("All rows, columns 'Feature_B' and 'Target':")
display(df.loc[:, ['Feature_B', 'Target']])

# Conditional selection with loc
print("Rows where 'Feature_A' is greater than 50:")
display(df.loc[df['Feature_A'] > 50])

# Conditional selection with loc and specific columns
print("Rows where 'Category' is 'A', showing 'Feature_A' and 'Target':")
display(df.loc[df['Category'] == 'A', ['Feature_A', 'Target']])

Row with label 0:

Feature_A                     10
Feature_B                    1.1
Category                       A
Target                         0
Date         2023-01-01 00:00:00
Name: 0, dtype: object

Rows with labels 0, 2, 5:

   Feature_A  Feature_B Category  Target       Date
0         10        1.1        A       0 2023-01-01
2         30        NaN        A       0 2023-01-03
5         60        6.6        A       1 2023-01-06

Rows from label 2 to 5 (inclusive):

   Feature_A  Feature_B Category  Target       Date
2         30        NaN        A       0 2023-01-03
3         40        4.4        C       1 2023-01-04
4         50        5.5        B       0 2023-01-05
5         60        6.6        A       1 2023-01-06

Rows 0 to 3, columns 'Feature_A' and 'Category':

   Feature_A Category
0         10        A
1         20        B
2         30        A
3         40        C

All rows, columns 'Feature_B' and 'Target':

   Feature_B  Target
0        1.1       0
1        2.2       1
2        NaN       0
3        4.4       1
4        5.5       0
5        6.6       1
6        7.7       0
7        NaN       1
8        9.9       0
9       10.0       1

Rows where 'Feature_A' is greater than 50:

   Feature_A  Feature_B Category  Target       Date
5         60        6.6        A       1 2023-01-06
6         70        7.7        C       0 2023-01-07
7         80        NaN        B       1 2023-01-08
8         90        9.9        A       0 2023-01-09
9        100       10.0        C       1 2023-01-10

Rows where 'Category' is 'A', showing 'Feature_A' and 'Target':

   Feature_A  Target
0         10       0
2         30       0
5         60       1
8         90       0

#### `iloc` (Integer-location based indexing)
Used for selecting data by the integer position of rows and columns. It excludes the end position (like standard Python slicing).

`df.iloc[row_index_position, column_index_position]`

In [6]:
# Select a single row by integer position
print("Row at integer position 0:")
display(df.iloc[0])

# Select multiple rows by integer positions
print("Rows at integer positions 0, 2, 5:")
display(df.iloc[[0, 2, 5]])

# Select a slice of rows by integer position (exclusive end)
print("Rows from integer position 2 up to (but not including) 5:")
display(df.iloc[2:5])

# Select rows and specific columns by integer position
# Column 'Feature_A' is at index 0, 'Category' at index 2
print("Rows 0 to 3, columns at integer positions 0 and 2:")
display(df.iloc[0:4, [0, 2]])

# Select all rows, specific columns by integer position
# Column 'Feature_B' is at index 1, 'Target' at index 3
print("All rows, columns at integer positions 1 and 3:")
display(df.iloc[:, [1, 3]])

Row at integer position 0:

Feature_A                     10
Feature_B                    1.1
Category                       A
Target                         0
Date         2023-01-01 00:00:00
Name: 0, dtype: object

Rows at integer positions 0, 2, 5:

   Feature_A  Feature_B Category  Target       Date
0         10        1.1        A       0 2023-01-01
2         30        NaN        A       0 2023-01-03
5         60        6.6        A       1 2023-01-06

Rows from integer position 2 up to (but not including) 5:

   Feature_A  Feature_B Category  Target       Date
2         30        NaN        A       0 2023-01-03
3         40        4.4        C       1 2023-01-04
4         50        5.5        B       0 2023-01-05

Rows 0 to 3, columns at integer positions 0 and 2:

   Feature_A Category
0         10        A
1         20        B
2         30        A
3         40        C

All rows, columns at integer positions 1 and 3:

   Feature_B  Target
0        1.1       0
1        2.2       1
2        NaN       0
3        4.4       1
4        5.5       0
5        6.6       1
6        7.7       0
7        NaN       1
8        9.9       0
9       10.0       1

#### Alternatives to `loc` and `iloc` (Contextual)

While `loc` and `iloc` are the primary and most robust ways for selection, other methods can achieve similar results in specific contexts.

*   **Direct Column Selection:** For selecting columns by name.
*   **Boolean Indexing:** For selecting rows based on conditions.
*   **`[]` operator:** For basic row slicing or column selection.
*   **`.at` and `.iat`:** For single value lookup, optimized for speed.

In [7]:
print("### Alternatives / Related methods ###")

# 1. Direct Column Selection (using [])
print("\nSelect 'Feature_A' column:")
display(df['Feature_A'].head())

print("\nSelect multiple columns ['Feature_A', 'Target']:")
display(df[['Feature_A', 'Target']].head())

# 2. Boolean Indexing (often combined with [])
print("\nRows where 'Target' is 1:")
display(df[df['Target'] == 1])

# Combining conditions
print("\nRows where 'Feature_A' > 50 AND 'Category' is 'C':")
display(df[(df['Feature_A'] > 50) & (df['Category'] == 'C')])

# 3. Simple Slicing (for rows using integer position)
print("\nRows from index 1 to 4 (using simple slicing, like iloc):")
display(df[1:5]) # Equivalent to df.iloc[1:5]

# 4. `.at` (for single label lookup, faster than loc for single element)
print("\nValue at row label 0, column 'Feature_A' using .at:")
print(df.at[0, 'Feature_A'])

# 5. `.iat` (for single integer-position lookup, faster than iloc for single element)
print("\nValue at row position 0, column position 0 ('Feature_A') using .iat:")
print(df.iat[0, 0])

### Alternatives / Related methods ###

Select 'Feature_A' column:

0    10
1    20
2    30
3    40
4    50
Name: Feature_A, dtype: int64

Select multiple columns ['Feature_A', 'Target']:

   Feature_A  Target
0         10       0
1         20       1
2         30       0
3         40       1
4         50       0

Rows where 'Target' is 1:

   Feature_A  Feature_B Category  Target       Date
1         20        2.2        B       1 2023-01-02
3         40        4.4        C       1 2023-01-04
5         60        6.6        A       1 2023-01-06
7         80        NaN        B       1 2023-01-08
9        100       10.0        C       1 2023-01-10

Rows where 'Feature_A' > 50 AND 'Category' is 'C':

   Feature_A  Feature_B Category  Target       Date
6         70        7.7        C       0 2023-01-07
9        100       10.0        C       1 2023-01-10

Rows from index 1 to 4 (using simple slicing, like iloc):

   Feature_A  Feature_B Category  Target       Date
1         20        2.2        B       1 2023-01-02
2         30        NaN        A       0 2023-01-03
3         40        4.4        C       1 2023-01-04
4         50        5.5        B       0 2023-01-05

Value at row label 0, column 'Feature_A' using .at:
10

Value at row position 0, column position 0 ('Feature_A') using .iat:
10

### 5. Feature Engineering: Creating New Features

Deriving new features from existing ones can significantly improve model performance.

In [8]:
# Creating a new feature 'Feature_C' by combining 'Feature_A' and 'Feature_B'
df['Feature_C'] = df['Feature_A'] * df['Feature_B']

# Creating a binary feature based on a condition
df['Is_Large_Feature_A'] = (df['Feature_A'] > 50).astype(int)

# Extracting features from Date column
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df['DayOfWeek'] = df['Date'].dt.dayofweek # Monday=0, Sunday=6

print("DataFrame after Feature Engineering:")
display(df.head())

DataFrame after Feature Engineering:

,Feature_A,Feature_B,Category,Target,Date,Feature_C,Is_Large_Feature_A,Year,Month,Day,DayOfWeek
0,10,1.1,A,0,2023-01-01,11.0,0,2023,1,1,6
1,20,2.2,B,1,2023-01-02,44.0,0,2023,1,2,0
2,30,NaN,A,0,2023-01-03,NaN,0,2023,1,3,1
3,40,4.4,C,1,2023-01-04,176.0,0,2023,1,4,2
4,50,5.5,B,0,2023-01-05,275.0,0,2023,1,5,3

### 6. Grouping and Aggregation

`groupby()` is essential for summarizing data by categories.

In [9]:
# Group by 'Category' and calculate the mean of numerical features
print("Mean of features grouped by 'Category':")
display(df.groupby('Category')[['Feature_A', 'Feature_C']].mean())

# Group by 'Category' and apply multiple aggregation functions
print("\nMultiple aggregations by 'Category':")
display(df.groupby('Category').agg(
    Feature_A_mean=('Feature_A', 'mean'),
    Feature_C_sum=('Feature_C', 'sum'),
    Count=('Feature_A', 'count')
))

# Group by 'DayOfWeek' and calculate average 'Feature_A'
print("\nAverage Feature_A by Day of Week:")
display(df.groupby('DayOfWeek')['Feature_A'].mean())

Mean of features grouped by 'Category':

          Feature_A   Feature_C
Category
A              47.5  432.666667
B              50.0  159.500000
C              70.0  571.666667

Multiple aggregations by 'Category':

          Feature_A_mean  Feature_C_sum  Count
Category
A                   47.5         1298.0      4
B                   50.0          319.0      3
C                   70.0         1715.0      3

Average Feature_A by Day of Week:

DayOfWeek
0    55.0
1    65.0
2    40.0
3    50.0
4    60.0
5    70.0
6    45.0
Name: Feature_A, dtype: float64

### 7. Data Transformation (`apply`, `map`, `applymap`)

These methods are used to apply functions to DataFrame elements, Series, or DataFrames.

In [10]:
# .apply(): Apply a function along an axis of the DataFrame or Series
# Apply a lambda function to a column
df['Feature_A_Squared'] = df['Feature_A'].apply(lambda x: x**2)
print("DataFrame with 'Feature_A_Squared' using .apply():")
display(df.head())

# Apply a custom function to multiple columns
def custom_transform(row):
    return row['Feature_A'] + row['Feature_B'] if pd.notnull(row['Feature_B']) else row['Feature_A']

df['Transformed_Feature'] = df.apply(custom_transform, axis=1)
print("\nDataFrame with 'Transformed_Feature' using .apply() on rows:")
display(df.head())

# .map(): Map values of a Series to other values
# Create a mapping dictionary
category_mapping = {'A': 'Group1', 'B': 'Group2', 'C': 'Group3'}
df['Category_Mapped'] = df['Category'].map(category_mapping)
print("\nDataFrame with 'Category_Mapped' using .map():")
display(df.head())

# .applymap() (for element-wise application on DataFrame, deprecated in favor of .apply(lambda x: x.apply(func), axis=...) or vectorized operations)
# df_numeric = df[['Feature_A', 'Feature_C']].copy()
# df_numeric_plus_one = df_numeric.applymap(lambda x: x + 1)
# print("\nDataFrame with numeric features + 1 using .applymap():")
# display(df_numeric_plus_one)

DataFrame with 'Feature_A_Squared' using .apply():

,Feature_A,Feature_B,Category,Target,Date,Feature_C,Is_Large_Feature_A,Year,Month,Day,DayOfWeek,Feature_A_Squared
0,10,1.1,A,0,2023-01-01,11.0,0,2023,1,1,6,100
1,20,2.2,B,1,2023-01-02,44.0,0,2023,1,2,0,400
2,30,NaN,A,0,2023-01-03,NaN,0,2023,1,3,1,900
3,40,4.4,C,1,2023-01-04,176.0,0,2023,1,4,2,1600
4,50,5.5,B,0,2023-01-05,275.0,0,2023,1,5,3,2500

DataFrame with 'Transformed_Feature' using .apply() on rows:

,Feature_A,Feature_B,Category,Target,Date,Feature_C,Is_Large_Feature_A,Year,Month,Day,DayOfWeek,Feature_A_Squared,Transformed_Feature
0,10,1.1,A,0,2023-01-01,11.0,0,2023,1,1,6,100,11.1
1,20,2.2,B,1,2023-01-02,44.0,0,2023,1,2,0,400,22.2
2,30,NaN,A,0,2023-01-03,NaN,0,2023,1,3,1,900,30.0
3,40,4.4,C,1,2023-01-04,176.0,0,2023,1,4,2,1600,44.4
4,50,5.5,B,0,2023-01-05,275.0,0,2023,1,5,3,2500,55.5

DataFrame with 'Category_Mapped' using .map():

,Feature_A,Feature_B,Category,Target,Date,Feature_C,Is_Large_Feature_A,Year,Month,Day,DayOfWeek,Feature_A_Squared,Transformed_Feature,Category_Mapped
0,10,1.1,A,0,2023-01-01,11.0,0,2023,1,1,6,100,11.1,Group1
1,20,2.2,B,1,2023-01-02,44.0,0,2023,1,2,0,400,22.2,Group2
2,30,NaN,A,0,2023-01-03,NaN,0,2023,1,3,1,900,30.0,Group1
3,40,4.4,C,1,2023-01-04,176.0,0,2023,1,4,2,1600,44.4,Group3
4,50,5.5,B,0,2023-01-05,275.0,0,2023,1,5,3,2500,55.5,Group2

### 8. Merging and Joining DataFrames

Combining data from different sources is a common task.

In [11]:
# Create another DataFrame for merging demonstration
df_B = pd.DataFrame({
    'Category': ['A', 'B', 'C', 'D'],
    'Category_Description': ['Alpha', 'Beta', 'Gamma', 'Delta']
})

# Merge df with df_B based on 'Category'
# default is inner join
df_merged = pd.merge(df, df_B, on='Category', how='left')
print("DataFrame after left merge with df_B:")
display(df_merged.head())

# Example of different join types: 'inner', 'outer', 'left', 'right'
# df_inner = pd.merge(df, df_B, on='Category', how='inner')
# df_outer = pd.merge(df, df_B, on='Category', how='outer')
# df_right = pd.merge(df, df_B, on='Category', how='right')

DataFrame after left merge with df_B:

,Feature_A,Feature_B,Category,Target,Date,Feature_C,Is_Large_Feature_A,Year,Month,Day,DayOfWeek,Feature_A_Squared,Transformed_Feature,Category_Mapped,Category_Description
0,10,1.1,A,0,2023-01-01,11.0,0,2023,1,1,6,100,11.1,Group1,Alpha
1,20,2.2,B,1,2023-01-02,44.0,0,2023,1,2,0,400,22.2,Group2,Beta
2,30,NaN,A,0,2023-01-03,NaN,0,2023,1,3,1,900,30.0,Group1,Alpha
3,40,4.4,C,1,2023-01-04,176.0,0,2023,1,4,2,1600,44.4,Group3,Gamma
4,50,5.5,B,0,2023-01-05,275.0,0,2023,1,5,3,2500,55.5,Group2,Beta

### 9. Pivoting and Melting

Reshaping data for analysis or modeling.

In [12]:
# .pivot_table(): Reshape data with aggregation
# Let's create a simpler df for pivot table demo
df_pivot_demo = pd.DataFrame({
    'City': ['NY', 'NY', 'SF', 'SF', 'LA'],
    'Month': ['Jan', 'Feb', 'Jan', 'Feb', 'Jan'],
    'Sales': [100, 150, 200, 120, 300]
})
print("Original df for pivot demo:")
display(df_pivot_demo)

pivot_table = df_pivot_demo.pivot_table(values='Sales', index='City', columns='Month', aggfunc='sum')
print("\nPivot Table (Sales by City and Month):")
display(pivot_table)

# .melt(): Unpivot a DataFrame from wide to long format
# Let's melt the pivot_table back (or similar)
melted_df = pivot_table.reset_index().melt(id_vars=['City'], var_name='Month', value_name='Sales')
print("\nMelted DataFrame from Pivot Table:")
display(melted_df)

Original df for pivot demo:

  City Month  Sales
0   NY   Jan    100
1   NY   Feb    150
2   SF   Jan    200
3   SF   Feb    120
4   LA   Jan    300

Pivot Table (Sales by City and Month):

Month    Feb    Jan
City
LA       NaN  300.0
NY     150.0  100.0
SF     120.0  200.0

Melted DataFrame from Pivot Table:

  City Month  Sales
0   LA   Feb    NaN
1   NY   Feb  150.0
2   SF   Feb  120.0
3   LA   Jan  300.0
4   NY   Jan  100.0
5   SF   Jan  200.0

### 10. Data Type Conversion

Ensuring correct data types (`dtypes`) is crucial for memory efficiency and correct operations.

In [13]:
# .astype(): Convert a column to a specific data type
print("Original dtypes:")
display(df.dtypes)

df['Feature_A'] = df['Feature_A'].astype(float)
df['Target'] = df['Target'].astype(bool)

print("\nNew dtypes after conversion:")
display(df.dtypes)

# pd.to_datetime(), pd.to_numeric(), pd.to_timedelta()
# These are specialized functions for robust type conversion
# Example: Converting a column to datetime (already done for 'Date')
# df['Another_Date_Col'] = pd.to_datetime(df['Another_Date_Col'], errors='coerce')

Original dtypes:

Feature_A                       int64
Feature_B                     float64
Category                       object
Target                          int64
Date                   datetime64[ns]
Feature_C                     float64
Is_Large_Feature_A              int64
Year                            int32
Month                           int32
Day                             int32
DayOfWeek                       int32
Feature_A_Squared               int64
Transformed_Feature           float64
Category_Mapped                object
dtype: object

New dtypes after conversion:

Feature_A                     float64
Feature_B                     float64
Category                       object
Target                           bool
Date                   datetime64[ns]
Feature_C                     float64
Is_Large_Feature_A              int64
Year                            int32
Month                           int32
Day                             int32
DayOfWeek                       int32
Feature_A_Squared               int64
Transformed_Feature           float64
Category_Mapped                object
dtype: object

### Conclusion

This covers many of the core pandas functionalities for data preparation in AI/ML. Mastering these methods will enable you to efficiently clean, transform, and analyze your datasets, forming a strong foundation for building robust models.